version: "3.7"

x-default-variables: &default-variables
  LOG_LEVEL: ${LOG_LEVEL-INFO}
  LOG_FORMAT: ${LOG_FORMAT-json}
  MANIFEST_PATH: ${MANIFEST_PATH-/manifests}
  TEST_DATA: ${TEST_DATA-}
  HTTP_PORT: ${HTTP_PORT-}
  HTTP_HOST: ${HTTP_HOST-0.0.0.0}
  HEALTH_PORT: ${HEALTH_PORT-}
  DB_TLS_SSLMODE: ${DB_TLS_SSLMODE-}
  DB_TLS_CERT: ${DB_TLS_CERT-}
  DB_TLS_KEY: ${DB_TLS_KEY-}
  DB_TLS_CA: ${DB_TLS_CA-}
  DB_HOST: ${DB_HOST-}
  DB_PORT: ${DB_PORT-}
  DB_DATABASE: ${DB_DATABASE-}
  DB_POOLSIZE: ${DB_POOLSIZE-}
  DB_POOL_TIMEOUT: ${DB_POOL_TIMEOUT-}

x-container-common: &container-common
  image: golang:1.15-buster
  restart: ${CONTAINER_RESTART-on-failure}
  entrypoint: /bin/main
  tty: true
  networks:
    - quorum
    - besu
    - hashicorp

services:
  key-manager:
    <<: *container-common
    environment:
      <<: *default-variables
    ports:
      - 8080:8080
      - 8081:8081
    restart: "no"
    command: run
    volumes:
      - ./build/bin/key-manager:/bin/main:ro
      - ./deps/config:/manifests:ro
      - hashicorp-token:/vault/token:ro

  generate-jwt:
    <<: *container-common
    environment:
      <<: *default-variables
      AUTH_OICD_CA_CERT: ${AUTH_OICD_CA_CERT-/certificates/cert.pem}
      AUTH_OICD_CA_KEY: ${AUTH_OICD_CA_KEY-/certificates/key.pem}
    volumes:
      - ./build/bin/key-manager:/bin/main:ro
      - ./tests/utils/certificates:/certificates:ro
    command: utils generate-jwt --username=${USERNAME-username} --groups=${GROUPS-admin,user} --expiration=${EXPIRATION-24h}
    restart: "no"

networks:
  quorum:
    external:
      name: quorum
  besu:
    external:
      name: besu
  hashicorp:
    external:
      name: hashicorp

volumes:
  hashicorp-token:
    external:
      name: hashicorp-token

